name: calculator
description: A private calculator

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  collection: ^1.15.0
  android_intent: ^2.0.2
  prompt_dialog: ^1.0.0
  hive: ^2.0.4
  path_provider: ^2.0.2
  permission_handler: ^8.1.2
  volume_control: ^0.1.5
  user_command: ^0.0.3
  video_player: ^2.1.10
  network_info_plus: ^3.0.2
  uuid: ^3.0.7
  flutter_lints: ^2.0.1
  path: ^1.8.2
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  given_when_then_unit_test: ^0.1.0
  shouldly: ^0.5.0+1

flutter:
  uses-material-design: true

flutter_icons:
  image_path: "icon/icon.png"
  android: true